[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    baseUrl = "https://www.ornekciceksitesi.com"

[plugins.inputs]
    baseUrl = "https://ornekciceksitesi.com"
    exclude = ["/google*.html"]
